import type { Metadata } from "next";
import { DM_Serif_Display, Montserrat, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SmoothScrollProvider from "@/components/provider/SmoothScrollprovider";
import NextTopLoader from "nextjs-toploader";
import { QueryClientProvider } from "@/components/provider/QueryClientProvider";
import AuthSessionProvider from "@/components/provider/AuthSessionProvider";
import { Toaster } from "@/components/ui/sonner";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dm-serif",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "BubbleDrive",
  description: "Generated by create next app",
  icons: {
    icon: "/wfav.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        dmSerif.variable,
        montserrat.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body>
        <NextTopLoader color="#004EB0" height={3} showSpinner={false} />
        <QueryClientProvider>
          <SmoothScrollProvider>
            <AuthSessionProvider>{children}</AuthSessionProvider>
            <Toaster />
          </SmoothScrollProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
